### PR TITLE
Update ghcs

### PR DESCRIPTION
**Pull request by tmcgilchrist**
A few changes in here:
 * add ghc 8.4.3 to travis
 * bump upper bound of singletons
 * fix duplicate imports of `natVal`

On the last point I'm not entirely convinced I've chosen the right source of `natVal`. An example of the compile error is:
```haskell
 test/Test/Grenade/Network.hs:364:40: error:
    Ambiguous occurrence ‘natVal’
    It could refer to either ‘Data.Singletons.TypeLits.natVal’,
                             imported from ‘Data.Singletons.TypeLits’ at test/Test/Grenade/Network.hs:24:1-41
                             (and originally defined in ‘GHC.TypeNats’)
                          or ‘GHC.TypeLits.natVal’,
                             imported from ‘GHC.TypeLits’ at test/Test/Grenade/Network.hs:35:1-29
    |
364 |                         let output_f = natVal f
    |                                        ^^^^^^

```

with the two type signatures being:
 * `GHC.TypeLits.natVal :: forall n proxy. KnownNat n => proxy n -> Integer`
 * `Data.Singletons.TypeLits.natVal :: KnownNat n => proxy n -> Natural`

The change to `Natural` in `singletons` causes some issues in the test cases, which is why the tests use `GHC.TypeLits.natVal` rather than the singletons version.

### CODE REVIEW

**Comment by HuwCampbell** [comment]
Thanks Tim!

I think this might be problematic though, it looks like the singletons library switched its export of natval from `GHC.TypeLits` to `GHC.TypeNats` in version 2.4. So This is going to pull in different definitions depending on which compiler one is using.

The TypeNats one has existed for long enough, so maybe we should just swap to that for all the compilers.

**Comment by erikd** [comment]
I didn't see this PR, but i fixed everything to build with 8.4.3 in #75

**Comment by HuwCampbell** [comment]
Thanks guys.

I'm still a bit iffy on using the Natural version in 8.2 and above, and the Integer version in 7.10 and 8.0; but I'm not sure there's a great way around that apart from dropping support for the older ones.

I'll merge the other PR. I would prefer to use Natural going forwards.

**Comment by erikd** [comment]
:-1:
